# Stage 1: Compile and Build angular codebase

# Use official node image as the base image
FROM node:latest as build-stage

# Set the working directory inside container
WORKDIR /app

COPY package*.json /app/

# Install all the dependencies
RUN npm install

# Add the source code to app
COPY ./ /app/


# Generate the build of the application
RUN npm run build


# Stage 2: Serve app with nginx server

# Use official nginx image as the base image
FROM nginx:latest

# Copy the build output to replace the default nginx contents.
#COPY --from=build /usr/local/app/dist/sample-angular-app /usr/share/nginx/html

COPY --from=build-stage /app/dist/ /usr/share/nginx/html
COPY --from=build-stage /app/nginx-custom.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80


# docker image build -t cpf-hmi:latest  .
# docker run -p 8000:80 cpf-hmi

